// Brands in the catalog, most products first (from the imported Allure range).
// `query` is the shop search that lists that brand's products.
export type Brand = { name: string; query: string; logo?: string };

export const brands: Brand[] = [
  { name: "Revuele", query: "revuele" },
  { name: "Beauty Formulas", query: "beauty formulas" },
  { name: "Cocodor", query: "cocodor" },
  { name: "Garnier", query: "garnier" },
  { name: "Face Facts", query: "face facts" },
  { name: "Zaron", query: "zaron" },
  { name: "Revox", query: "revox" },
  { name: "L.A. Girl", query: "la girl" },
  { name: "NIVEA", query: "nivea" },
  { name: "Neutrogena", query: "neutrogena" },
  { name: "Simple", query: "simple" },
  { name: "Palmer’s", query: "palmers" },
  { name: "Cantu", query: "cantu" },
  { name: "Dove", query: "dove" },
  { name: "NYX", query: "nyx" },
  { name: "e.l.f.", query: "elf" },
  { name: "Fadeout", query: "fadeout" },
  { name: "Anua", query: "anua" },
  { name: "ORS", query: "ors" },
  { name: "Milani", query: "milani" },
  { name: "Balance Active", query: "balance active" },
  { name: "SKIN1004", query: "skin1004" },
  { name: "Olay", query: "olay" },
  { name: "Difeel", query: "difeel" },
  { name: "Carmex", query: "carmex" },
  { name: "Nineless", query: "nineless" },
  { name: "Jumiso", query: "jumiso" },
  { name: "Vaseline", query: "vaseline" },
  { name: "Beauty of Joseon", query: "beauty of joseon" },
  { name: "CeraVe", query: "cerave" },
  { name: "Creme of Nature", query: "creme of nature" },
  { name: "TRESemmé", query: "tresemm" },
  { name: "St. Ives", query: "st ives" },
  { name: "Clean & Clear", query: "clean and clear" },
  { name: "Advanced Clinicals", query: "advanced clinicals" },
  { name: "Dr Rashel", query: "dr rashel" },
  { name: "COSRX", query: "cosrx" },
  { name: "Aussie", query: "aussie" },
  { name: "Uncle Jimmy", query: "uncle jimmy" },
];
